dictionaryInformation = [[1, 'food', 8.75, 20], [2, 'water', 1.99, 49], [3, 'logitech mouse', 9.99, 14], [4, 'intro to python by tony gaddis', 70.0, 0], [36, 'lord of the rings', 69.0, 420]]
listInformation = ['food', 'water', 'logitech mouse', 'intro to python by tony gaddis', 'lord of the rings']
shoppingCartInformation = []
cartHistoryInformation = []
userAccountInformation = [['jeremyR', '123', 0, 'user', [], []], ['sampleUser', '111', 0, 'user', [], []]]
